bicycle_store_web/Controllers/OrderController.cs
using bicycle_store_web.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace bicycle_store_web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IUserService userService;
        private readonly IOrderService orderService;
        public OrderController(IUserService userService, IOrderService orderService)
        {
            this.userService = userService;
            this.orderService = orderService;
        }
        public IActionResult UserOrders() => View();
        public IActionResult AdminOrders() => View();
        [HttpGet]
        public IActionResult GetAdminOrders()
        {
            var ResultList = orderService.GetAdminOrders().Select(o => new
            {
                o.OrderId,
                o.Bicycle.Name,
                o.Quantity,
                o.BicycleCost,
                o.Order.Status,
                o.Order.User.FullName
            }).ToList();
            return new JsonResult(new { data = ResultList });
        }
        [HttpGet]
        public IActionResult GetUserOrders()
        {
            var ResultList = orderService.GetUserOrders(userService.GetUserId(User.Identity.Name))
                .Select(o => new
                {
                    o.OrderId,
                    o.Bicycle.Name,
                    o.Quantity,
                    o.BicycleCost,
                    o.Order.Status,
                    o.Order.UserId,
                }).ToList();
            return new JsonResult(new { data = ResultList });
        }
        [HttpPost]
        public IActionResult CreateOrder()
        {
            if(orderService.CreateOrder(userService.GetUserId(User.Identity.Name)))
                return new JsonResult(new { success = true, message = "Order successfully created" });
            else
                return new JsonResult(new { success = false, message = "Error while creating order" });
        }
        [HttpPost]
        public IActionResult SendOrder(int OrderId)
        {
            if (orderService.SendOrder(OrderId))
                return new JsonResult(new { success = true, message = "Successfully sended" });
            else
                return new JsonResult(new { success = false, message = "Error while sending" });
        }
        [HttpPost]
        public IActionResult ConfirmReceipt(int OrderId)
        {
            if (orderService.ConfirmReceipt(OrderId))
                return new JsonResult(new { success = true, message = "Successfully confirmed" });
            else
                return new JsonResult(new { success = false, message = "Error while confirming" });
        }
    }
}

bicycle_store_web/Controllers/ShoppingCartController.cs
using bicycle_store_web.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System.Linq;

namespace bicycle_store_web.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartService shoppingCartService;
        private readonly IUserService userService;
        public ShoppingCartController(IShoppingCartService shoppingCartService, IUserService userService)
        {
            this.shoppingCartService = shoppingCartService;
            this.userService = userService;
        }
        [Authorize]
        public IActionResult Index() => View();
        [HttpGet]
        public IActionResult GetShoppingCart()
        {
			Log.Information($"{System.Reflection.MethodBase.GetCurrentMethod()} started");

			var list = shoppingCartService.GetShoppingCart(userService.GetUserId(User.Identity.Name)).
                Select(o => new
                {
                    o.Id,
                    o.Bicycle.Name,
                    o.Bicycle.Price,
                    o.Quantity
                }).ToList();
			Log.Information($"{System.Reflection.MethodBase.GetCurrentMethod()} finished");

			return new JsonResult(new { data = list });
        }
        public IActionResult AddToShoppingCart(int BicycleId)
        {
			Log.Information($"{System.Reflection.MethodBase.GetCurrentMethod()} started");

            JsonResult result;
            bool serviceResult = shoppingCartService.AddToShoppingCart(BicycleId, userService.GetUserId(User.Identity.Name));
			if (serviceResult)
                result = new JsonResult(new { success = true, message = "Successfully added to shopping cart" });
            else
                result = new JsonResult(new { success = false, message = "Error while adding to shopping cart" });

			Log.Information($"{System.Reflection.MethodBase.GetCurrentMethod()} finished");

			return result;
        }
        public IActionResult RemoveFromShoppingCart(int ShoppingCartOrderId)
        {
			Log.Information($"{System.Reflection.MethodBase.GetCurrentMethod()} started");

			JsonResult result;
			bool serviceResult = shoppingCartService.RemoveFromShoppingCart(ShoppingCartOrderId);
			if (serviceResult)
				result = new JsonResult(new { success = true, message = "Successfully removed from shopping cart" });
            else
				result = new JsonResult(new { success = false, message = "Error while removing from shopping cart" });

			Log.Information($"{System.Reflection.MethodBase.GetCurrentMethod()} finished");

			return result;
        }
    }
}

bicycle_store_web/Controllers/UserController.cs
using bicycle_store_web.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace bicycle_store_web.Controllers
{
    public class UserController : Controller
    {
        private readonly bicycle_storeContext _db;
        private readonly IUserService _userService;
        private readonly IBicycleService _bicycleService;
        [BindProperty]
        public User user { get; set; }
        [BindProperty]
        public Order order { get; set; }
        [BindProperty]
        public IFormFile img { get; set; }
        public void AddImages()
        {
            foreach (User u in _db.Users)
                SaveUser(u, null);
            _db.SaveChanges();
        }
        public IQueryable<Bicycle> AddData()
        {
            var bicycles = _db.Bicycles.AsNoTracking()
                .Include(t => t.Type)
                .Include(p => p.Producer)
                .Include(c => c.Country);
            foreach (Bicycle b in bicycles)
            {
                b.Type.Bicycles.Add(b);
                b.Producer.Bicycles.Add(b);
                b.Country.Bicycles.Add(b);
            }
            return bicycles;
        }
        public UserController(bicycle_storeContext context, IUserService _userService, IBicycleService _bicycleService)
        {
            _db = context;
            this._userService = _userService;
            this._bicycleService = _bicycleService;
            //AddImages();
        }
        public IActionResult Bicycles() => View("Bicycles", _bicycleService.GetBicycles());
        public IActionResult SetProfile() 
        {
            if (User.Identity.IsAuthenticated)
                user = _userService.GetById(_userService.GetUserId(User.Identity.Name));
            else
                user = new User();
            return View(user);
        }
        public IActionResult Register() {
            user = new User();
            return View("Register", user); 
        }
        [HttpGet]
        public IActionResult Login(string ReturnUrl) 
        {
            ViewData["returnUrl"] = ReturnUrl;
            return View(); 
        }
        public IActionResult Logout ()
        {
            HttpContext.SignOutAsync();
            return Redirect("Bicycles");
        }
        [HttpPost("User/Login")]
        public IActionResult IsLogin(string Username, string Password, string ReturnUrl)
        {
            user = _userService.GetById(_userService.GetUserId(Username));
            if(user != null && user.Password == Password)
            {
                HttpContext.SignInAsync(_userService.GetClaims(user));
                if ((user.Role == "Admin" || user.Role == "SuperAdmin") && ReturnUrl == null)
                    return Redirect("/Admin/Bicycles");
                return Redirect(ReturnUrl ?? "Bicycles");
            }
            return BadRequest();
        }
        [HttpPost]
        public IActionResult SaveUser(User user, IFormFile Photo)
        {
            if (ModelState.IsValid)
            {
                if (_userService.SaveUser(user, Photo))
                    return new JsonResult(new { success = true, message = "Successfully saved" });
            }

            return Json(new { success = false, message = "Error while saving" });
        }
        public IActionResult DeleteUser(int Id)
        {
            if (_userService.DeleteUser(Id))
                return new JsonResult(new { success = true, message = "Delete successful" });
            else
                return new JsonResult(new { success = false, message = "Error while Deleting" });
        }
        public IActionResult GetUserRole() => Json(new
        {
            data = _userService.GetUserRole(_userService.GetUserId(User.Identity.Name))
        });
        public IActionResult GetUserId() => Json(new
        {
            data = _userService.GetUserId(User.Identity.Name)
        });


        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

bicycle_store_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bicycle_store_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
</head>
<body>
    <header class="bg-dark">
        @Html.Partial("_Navbar")
    </header>
    
    @{ if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
        {
            <main class="row col-md-12">
                <aside class="col-md-2 bg-dark border-right" id="adminPanel">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Bicycles">@SharedLocalizer["bicycles"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Types">@SharedLocalizer["types"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Producers">@SharedLocalizer["producers"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Order" asp-action="AdminOrders">@SharedLocalizer["orders"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Users">@SharedLocalizer["users"]</a>
                        </li>
                    </ul>
                </aside>


                <article class="col-md-9 container mt-3 pb-3">
                    @RenderBody()
                </article>
            </main>
        }
        else
        {
            <main class="container mt-3 pb-3 ">
                @RenderBody()
            </main>
        }
    }

    <footer class="border-top footer text-white bg-dark">
        <div class="container">
            &copy; 2022 - Bicycle Store -
        </div>
    </footer>
    @*<script src="/path/to/cdn/jquery.slim.min.js"></script>
    <script src="/path/to/dist/row-merge-bundle.min.js"></script>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

bicycle_store_web/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow">
    <div class="justify-content-center col-md-2">
        <a class="navbar-brand text-white text-center" asp-area="" asp-controller="User" asp-action="Bicycles">Bicycle Store</a>
    </div>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between row">
        <ul class="navbar-nav flex-grow-1 col-md-10"></ul>
        <ul class="navbar-nav flex-grow-1">
            @{
                @using Microsoft.AspNetCore.Builder;
                @using Microsoft.AspNetCore.Localization;
                @using Microsoft.Extensions.Options;

                @inject IOptions<RequestLocalizationOptions> LocOptions
                var requestCulture = Context.Features.Get<IRequestCultureFeature>();
                var cultureItems = LocOptions.Value.SupportedUICultures
                .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
                .ToList();
            }
            @* <div>
                <form asp-controller="User"
                      asp-action="SetLanguage"
                      asp-route-returnUrl="@Context.Request.Path" method="post">
                    <select name="culture" onchange="this.form.submit();"
                            asp-for="@requestCulture.RequestCulture.UICulture.Name"
                            asp-items="cultureItems" class="form-select-sm">
                    </select>
                </form>
            </div> *@
            @{
                if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown" style="float:right;">
                        <a href="#" class="nav-link text-white">@User.Identity.Name</a>
                        <ul class="dropdown-content bg-dark list-unstyled">
                            <li>
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="SetProfile">@SharedLocalizer["change"] @SharedLocalizer["profile"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="ShoppingCart" asp-action="Index">@SharedLocalizer["shoppingCart"]</a>
                            </li>
                            <li>
                                <a class="nav-link text-white" asp-area="" asp-controller="Order" asp-action="UserOrders">@SharedLocalizer["orders"]</a>
                            </li>
                            <li>
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Logout">@SharedLocalizer["log out"]</a>
                            </li>
                        </ul>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="SetProfile">@SharedLocalizer["register"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Login" asp-route-ReturnUrl="@{
                        @Context.Request.Path
    }">@SharedLocalizer["log in"]</a>
                    </li>
                }
            }
        </ul>
    </div>
</nav>